/**
 * One-shot seeder: writes curated data/ files from the OpenRisk mockup dataset.
 * Run: node scripts/seed-data.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const write = (rel, data) => {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(data, null, 2) + "\n");
  console.log("wrote", rel);
};

const feeds = [
  { id: "defiscan", name: "DeFiScan", type: "rating", typeLabel: "R", focus: "Decentralization maturity framework: who controls keys, upgrades, and admin powers", url: "https://defiscan.info", methodologyUrl: "https://defiscan.info" },
  { id: "defipunkd", name: "DeFiPunk'd", type: "rating", typeLabel: "R", focus: "Multi-dimension registry: Control, Exit, Autonomy, Open Access, Verifiability via distributed LLM consensus", url: "https://defipunkd.com", methodologyUrl: "https://defipunkd.com" },
  { id: "credora", name: "Credora", type: "rating", typeLabel: "R", focus: "Institutional-grade credit risk ratings for DeFi protocols and borrowers", url: "https://credora.io", methodologyUrl: "https://credora.io" },
  { id: "sphere", name: "DeFi Sphere", type: "rating", typeLabel: "R", focus: "Multi-dimensional protocol analysis covering technical, financial, and operational risk", url: "https://defisphere.com", methodologyUrl: "https://defisphere.com" },
  { id: "xerberus", name: "Xerberus", type: "rating", typeLabel: "R", focus: "Independent risk rating protocol for DeFi vaults. 300+ subscores across 85+ mechanisms", url: "https://xerberus.io", methodologyUrl: "https://xerberus.io" },
  { id: "risklayer", name: "RiskLayer", type: "rating", typeLabel: "R", focus: "Economic security middleware on EigenLayer. Proof of Risk consensus, validator-attested scores", url: "https://risklayer.xyz", methodologyUrl: "https://risklayer.xyz" },
  { id: "philidor", name: "Philidor", type: "rating", typeLabel: "R", focus: "Deterministic vault risk scoring across 700+ vaults. Asset quality, code maturity, governance controls", url: "https://philidor.xyz", methodologyUrl: "https://philidor.xyz" },
  { id: "blockan", name: "BlockAnalitica", type: "dash", typeLabel: "D", focus: "Quantitative on-chain risk dashboards for lending markets: liquidations, collateral health, exposure", url: "https://blockanalitica.com", methodologyUrl: "https://blockanalitica.com" },
  { id: "curatorw", name: "CuratorWatch", type: "dash", typeLabel: "D", focus: "Vault-level risk monitoring for Morpho curators: allocation risk and curator behavior", url: "https://curatorwatch.com", methodologyUrl: "https://curatorwatch.com" },
  { id: "defisaver", name: "DeFi Saver", type: "dash", typeLabel: "D", focus: "Live loan health and liquidation statistics for leveraged DeFi positions", url: "https://defisaver.com", methodologyUrl: "https://defisaver.com" },
  { id: "pigi", name: "pigi.finance", type: "dash", typeLabel: "D", focus: "Vault analytics and risk-adjusted yield across 50+ protocols; exploit history, holder concentration", url: "https://pigi.finance", methodologyUrl: "https://pigi.finance" },
  { id: "zyfai", name: "Zyfai Risk", type: "dash", typeLabel: "D", focus: "Real-time risk dashboard for liquidity pools: risk metrics, TVL, APY, security grades", url: "https://zyfai.com", methodologyUrl: "https://zyfai.com" },
  { id: "pharos", name: "Pharos", type: "monitor", typeLabel: "M", focus: "Real-time risk monitoring and automated alerts for live protocol risk events", url: "https://pharos.xyz", methodologyUrl: "https://pharos.xyz" },
  { id: "llamarisk", name: "LlamaRisk", type: "research", typeLabel: "Ξ", focus: "Protocol risk research and parameter recommendations; collateral and governance risk", url: "https://llamarisk.com", methodologyUrl: "https://llamarisk.com" },
];

const categories = {
  lending: { id: "lending", name: "Lending", color: "#3987e5" },
  dex: { id: "dex", name: "DEX / AMM", color: "#d95926" },
  agg: { id: "agg", name: "Swap Aggregator", color: "#199e70" },
  yield: { id: "yield", name: "Yield / Vault", color: "#c98500" },
  lst: { id: "lst", name: "Liquid Staking", color: "#d55181" },
};

const protocols = [
  { id: "aave", name: "Aave", category: "lending", families: ["v3", "v4"], defillamaSlug: "aave", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "Aave Governance v3 — onchain AAVE/stkAAVE voting", provenance: "onchain" }, { key: "Upgradeability", value: "Upgradeable proxies behind Level-1 executor + timelock", provenance: "onchain" }, { key: "Emergency", value: "Guardian multisig can pause markets; scope documented", provenance: "docs" }], audits: [{ year: "2025", summary: "Certora — v4 core, formal verification", provenance: "docs" }, { year: "2024", summary: "Spearbit — v3.2 review", provenance: "docs" }], incidents: [{ year: "2023", summary: "Curve-pool CRV exposure stress — no bad debt materialized", severity: "ok" }] },
  { id: "spark", name: "Spark", category: "lending", families: ["SparkLend", "sUSDS"], defillamaSlug: "spark", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "Sky sub-DAO; parameters set via Sky executive votes", provenance: "onchain" }, { key: "Upgradeability", value: "Upgradeable via Sky governance spells, 48h delay", provenance: "onchain" }, { key: "Emergency", value: "Freezer module — emergency shutdown inherited from Sky", provenance: "docs" }], audits: [{ year: "2025", summary: "ChainSecurity — SparkLend markets", provenance: "docs" }, { year: "2024", summary: "Cantina competition — sUSDS", provenance: "docs" }], incidents: [] },
  { id: "morpho", name: "Morpho", category: "lending", families: ["Morpho Blue"], defillamaSlug: "morpho", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "Immutable core; MORPHO governance owns periphery only", provenance: "onchain" }, { key: "Upgradeability", value: "Morpho Blue singleton is non-upgradeable", provenance: "onchain" }, { key: "Emergency", value: "No pause on core; risk pushed to vault/curator layer", provenance: "docs" }], audits: [{ year: "2024", summary: "Spearbit + Cantina — Blue core", provenance: "docs" }, { year: "2023", summary: "Multiple firms — 25+ engagements", provenance: "selfrep" }], incidents: [{ year: "2025", summary: "Front-end bug intercepted by whitehat — $2.6M returned", severity: "ser" }] },
  { id: "fluid", name: "Fluid", category: "lending", families: ["Lending", "DEX"], defillamaSlug: "fluid", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "Instadapp/Fluid team multisig + INST governance", provenance: "docs" }, { key: "Upgradeability", value: "Upgradeable liquidity layer, timelocked", provenance: "docs" }, { key: "Emergency", value: "Guardian can pause new borrows", provenance: "selfrep" }], audits: [{ year: "2024", summary: "StateMind, MixBytes — liquidity layer", provenance: "docs" }], incidents: [] },
  { id: "gearbox", name: "Gearbox", category: "lending", families: ["v3"], defillamaSlug: "gearbox", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "GEAR token DAO with technical multisig", provenance: "onchain" }, { key: "Upgradeability", value: "Upgradeable credit facades, DAO-gated", provenance: "docs" }, { key: "Emergency", value: "Pausable credit managers", provenance: "docs" }], audits: [{ year: "2023", summary: "ChainSecurity — v3 core", provenance: "docs" }], incidents: [] },
  { id: "euler", name: "Euler", category: "lending", families: ["v2 / EVK"], defillamaSlug: "euler", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "Vault-level governors; EUL DAO on periphery", provenance: "onchain" }, { key: "Upgradeability", value: "EVK vaults immutable once deployed, per-vault config", provenance: "onchain" }, { key: "Emergency", value: "Per-vault pause via governor role", provenance: "docs" }], audits: [{ year: "2024", summary: "10+ firms + $1.25M Cantina competition — v2", provenance: "docs" }], incidents: [{ year: "2023", summary: "v1 flash-loan exploit — $197M taken, fully recovered", severity: "crit" }] },
  { id: "compound", name: "Compound", category: "lending", families: ["v2", "v3"], defillamaSlug: "compound-finance", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "COMP Governor Bravo — onchain voting", provenance: "onchain" }, { key: "Upgradeability", value: "Comet upgradeable via governance, timelock 2d", provenance: "onchain" }, { key: "Emergency", value: "Pause guardian multisig", provenance: "docs" }], audits: [{ year: "2023", summary: "OpenZeppelin — continuous engagement", provenance: "docs" }], incidents: [{ year: "2021", summary: "COMP distribution bug — ~$80M misdirected", severity: "ser" }] },
  { id: "liquity", name: "Liquity", category: "lending", families: ["v1", "v2"], defillamaSlug: "liquity", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "v1 fully immutable, zero governance", provenance: "onchain" }, { key: "Upgradeability", value: "None — contracts frozen at deploy", provenance: "onchain" }, { key: "Emergency", value: "None by design; recovery mode is algorithmic", provenance: "onchain" }], audits: [{ year: "2024", summary: "ChainSecurity, Coinspect — v2/BOLD", provenance: "docs" }, { year: "2021", summary: "Trail of Bits — v1", provenance: "docs" }], incidents: [{ year: "2025", summary: "v2 stability pool bug — funds frozen, migration to v2.1", severity: "ser" }] },
  { id: "uniswap", name: "Uniswap", category: "dex", families: ["v3", "v4", "UniswapX"], defillamaSlug: "uniswap", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "UNI Governor; core pools permissionless", provenance: "onchain" }, { key: "Upgradeability", value: "v3/v4 core immutable; hooks are per-pool code", provenance: "onchain" }, { key: "Emergency", value: "None on core contracts", provenance: "onchain" }], audits: [{ year: "2024", summary: "OpenZeppelin, Certora, ABDK + $15.5M competition — v4", provenance: "docs" }], incidents: [] },
  { id: "curve", name: "Curve", category: "dex", families: ["AMM", "crvUSD"], defillamaSlug: "curve-dex", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "veCRV DAO — onchain parameter votes", provenance: "onchain" }, { key: "Upgradeability", value: "Pools immutable; new factories via DAO", provenance: "onchain" }, { key: "Emergency", value: "EmergencyDAO can kill gauges ≤2 months old", provenance: "docs" }], audits: [{ year: "2024", summary: "ChainSecurity — crvUSD, twocrypto-ng", provenance: "docs" }], incidents: [{ year: "2023", summary: "Vyper compiler reentrancy — ~$70M across pools, most recovered", severity: "crit" }] },
  { id: "balancer", name: "Balancer", category: "dex", families: ["v2", "v3"], defillamaSlug: "balancer", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "veBAL governance + ops multisigs", provenance: "onchain" }, { key: "Upgradeability", value: "Vault immutable; periphery via authorizer", provenance: "docs" }, { key: "Emergency", value: "Emergency sub-DAO can pause pools", provenance: "docs" }], audits: [{ year: "2024", summary: "Certora, Trail of Bits — v3", provenance: "docs" }], incidents: [{ year: "2025", summary: "v2 composable-pool rounding exploit — ~$116M drained", severity: "crit" }] },
  { id: "cowswap", name: "CoW Swap", category: "agg", families: ["CoW Protocol"], defillamaSlug: "cow-protocol", volumeMetric: true, tvlWithin: null, governance: [{ key: "Control", value: "CoW DAO; solver set permissioned by governance", provenance: "onchain" }, { key: "Upgradeability", value: "Settlement contract non-upgradeable", provenance: "onchain" }, { key: "Emergency", value: "Solver slashing + removal via DAO", provenance: "docs" }], audits: [{ year: "2023", summary: "G0 Group — settlement", provenance: "docs" }], incidents: [{ year: "2023", summary: "Solver exploit — ~$166K, slashed & patched", severity: "ser" }] },
  { id: "oneinch", name: "1inch", category: "agg", families: ["AggRouter v6", "LOP"], defillamaSlug: "1inch-network", volumeMetric: true, tvlWithin: null, governance: [{ key: "Control", value: "1inch DAO + team multisig on router deploys", provenance: "docs" }, { key: "Upgradeability", value: "Routers immutable; new versions deployed alongside", provenance: "docs" }, { key: "Emergency", value: "None — users approve per-router", provenance: "docs" }], audits: [{ year: "2024", summary: "OpenZeppelin — AggRouter v6", provenance: "docs" }], incidents: [{ year: "2025", summary: "Fusion resolver compromise — ~$5M, mostly returned", severity: "ser" }] },
  { id: "zerox", name: "0x / Matcha", category: "agg", families: ["0x v4", "Matcha"], defillamaSlug: "0x", volumeMetric: true, tvlWithin: null, governance: [{ key: "Control", value: "0x Labs multisig + ZRX governance (legacy)", provenance: "docs" }, { key: "Upgradeability", value: "Exchange proxy upgradeable via 0x governance timelock", provenance: "docs" }, { key: "Emergency", value: "Feature-level pause", provenance: "docs" }], audits: [{ year: "2021", summary: "ConsenSys Diligence — exchange proxy", provenance: "docs" }], incidents: [{ year: "2019", summary: "v2 signature validator bug — paused, no loss", severity: "ok" }] },
  { id: "yearn", name: "Yearn", category: "yield", families: ["v3"], defillamaSlug: "yearn-finance", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "veYFI + multisig-executed governance", provenance: "docs" }, { key: "Upgradeability", value: "v3 vaults immutable, strategies swappable", provenance: "docs" }, { key: "Emergency", value: "Guardian can shutdown vaults", provenance: "docs" }], audits: [{ year: "2023", summary: "ChainSecurity — v3 core", provenance: "docs" }], incidents: [{ year: "2021", summary: "v1 DAI vault exploit — $11M", severity: "ser" }] },
  { id: "mellow", name: "Mellow", category: "yield", families: ["LRT vaults"], defillamaSlug: "mellow", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "Mellow multisig + curator roles per vault", provenance: "selfrep" }, { key: "Upgradeability", value: "Upgradeable vault system, timelocked admin", provenance: "docs" }, { key: "Emergency", value: "Curator emergency withdrawal paths", provenance: "selfrep" }], audits: [{ year: "2024", summary: "ChainSecurity, Statemind — LRT vaults", provenance: "docs" }], incidents: [] },
  { id: "morphovaults", name: "Morpho Vaults", category: "yield", families: ["MetaMorpho"], defillamaSlug: null, volumeMetric: false, tvlWithin: "morpho", governance: [{ key: "Control", value: "Per-vault curator with public role; timelocked caps", provenance: "onchain" }, { key: "Upgradeability", value: "Vault code immutable; allocations curator-set", provenance: "onchain" }, { key: "Emergency", value: "Guardian veto on curator actions (if set)", provenance: "onchain" }], audits: [{ year: "2024", summary: "Spearbit — MetaMorpho", provenance: "docs" }], incidents: [{ year: "2026", summary: "Curator concentration event — one vault 94% single-market", severity: "ser" }] },
  { id: "pendle", name: "Pendle", category: "yield", families: ["v2"], defillamaSlug: "pendle", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "vePENDLE governance + team multisig", provenance: "docs" }, { key: "Upgradeability", value: "Upgradeable markets behind timelock", provenance: "docs" }, { key: "Emergency", value: "Pausing guardian on new listings", provenance: "selfrep" }], audits: [{ year: "2023", summary: "ChainSecurity, Spearbit — v2", provenance: "docs" }], incidents: [] },
  { id: "lido", name: "Lido", category: "lst", families: ["stETH", "wstETH"], defillamaSlug: "lido", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "LDO DAO + dual governance (stETH holder veto)", provenance: "onchain" }, { key: "Upgradeability", value: "Upgradeable core behind DAO vote + timelock", provenance: "onchain" }, { key: "Emergency", value: "GateSeal emergency pause, expiring committee", provenance: "docs" }], audits: [{ year: "2024", summary: "Statemind, Certora — dual governance", provenance: "docs" }], incidents: [{ year: "2025", summary: "One oracle key compromised — quorum held, no impact", severity: "ok" }] },
  { id: "rocketpool", name: "Rocket Pool", category: "lst", families: ["rETH"], defillamaSlug: "rocket-pool", volumeMetric: false, tvlWithin: null, governance: [{ key: "Control", value: "pDAO/oDAO split; RPL votes onchain", provenance: "onchain" }, { key: "Upgradeability", value: "Upgradeable via oDAO-executed governance", provenance: "docs" }, { key: "Emergency", value: "oDAO can pause deposits", provenance: "docs" }], audits: [{ year: "2024", summary: "Sigma Prime — Saturn upgrades", provenance: "docs" }], incidents: [] },
];

/** coverage: protocolId → feedId → { status, label?, verbatim?, asOf?, sourceUrl? } */
const rawCov = {
  aave: { defiscan: ["c", "Stage 1", "Stage 1 — upgradeability constrained by onchain governance with ≥7d exit window for users.", "2026-07"], defipunkd: ["c", "4/5", "Passes Control, Exit, Open Access, Verifiability. Autonomy partial: oracle dependency on Chainlink.", "2026-06"], credora: ["c", "AA−", "Credit rating AA− (stable). Deep liquidity, conservative LTVs, proven liquidation engine.", "2026-08"], sphere: ["c", "A−", "Technical A, financial A−, operational B+. Composite A− across 41 indicators.", "2026-05"], xerberus: ["p", "◐", "Rated at market level only: aWETH, aUSDC pools. Protocol-level rating pending.", "2026-07"], risklayer: ["c", "87", "Proof-of-Risk attested score 87/100 across 12 validators, dispute window clean.", "2026-08"], philidor: ["n"], blockan: ["c", "live", "Live dashboard: market exposure, liquidation depth, collateral-at-risk simulations.", "live"], curatorw: ["n"], defisaver: ["c", "live", "Position health tracking + automation live for v3 markets.", "live"], pigi: ["c", "live", "Vault analytics live: risk-adjusted APY percentile 71, exploit history clean.", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Monitored: 14 alert rules, 2 informational alerts past 30d.", "live"], llamarisk: ["c", "8 rpt", "8 published reports incl. GHO collateral review and E-mode parameter recommendations.", "2026-06"] },
  spark: { defiscan: ["c", "Stage 0", "Stage 0 — upgradeable via Sky spells without dedicated user exit window.", "2026-07"], defipunkd: ["c", "3/5", "Passes Open Access, Verifiability, Exit. Control and Autonomy inherit Sky governance surface.", "2026-06"], credora: ["c", "A", "Credit rating A. Sky backstop and PSM depth offset governance concentration.", "2026-08"], sphere: ["c", "B+", "Technical A−, operational B: subDAO dependency flagged.", "2026-05"], xerberus: ["p", "◐", "sUSDS vault rated BB+; SparkLend markets unrated.", "2026-07"], risklayer: ["n"], philidor: ["p", "◐", "sUSDS scored 6.8/10; lending side out of scope (not a vault).", "2026-06"], blockan: ["c", "live", "Live dashboard: D3M exposure, collateral health, liquidation curves.", "live"], curatorw: ["n"], defisaver: ["c", "live", "SparkLend position management live.", "live"], pigi: ["c", "live", "sUSDS tracked: risk-adjusted yield rank 12/50.", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Monitored: 9 alert rules, quiet 30d.", "live"], llamarisk: ["c", "4 rpt", "4 reports incl. sUSDS reserve composition review.", "2026-04"] },
  morpho: { defiscan: ["c", "Stage 1", "Stage 1 — immutable core; residual risk lives in curator layer, documented exit paths.", "2026-07"], defipunkd: ["c", "5/5", "Passes all five dimensions. Immutable singleton, permissionless market creation.", "2026-06"], credora: ["c", "A−", "Credit rating A−. Isolated-market design limits contagion; curator quality varies.", "2026-08"], sphere: ["c", "A−", "Technical A. Operational B+ on curator concentration.", "2026-05"], xerberus: ["p", "◐", "Rated via vault layer; core protocol out of rating scope.", "2026-07"], risklayer: ["c", "78", "Attested 78/100; deduction for oracle heterogeneity across markets.", "2026-08"], philidor: ["n"], blockan: ["c", "live", "Live dashboard: per-market LLTV stress, oracle deviation tracking.", "live"], curatorw: ["p", "◐", "Curator-level coverage; core markets aggregated only.", "live"], defisaver: ["c", "live", "Morpho position automation live.", "live"], pigi: ["c", "live", "Tracked across 40+ markets.", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Monitored: oracle + utilization alerts, 1 warning past 30d.", "live"], llamarisk: ["c", "3 rpt", "3 reports on oracle configuration risk in long-tail markets.", "2026-05"] },
  fluid: { defiscan: ["c", "Stage 0", "Stage 0 — upgradeable liquidity layer with admin powers; timelock present, exit window short.", "2026-07"], defipunkd: ["c", "3/5", "Passes Open Access, Verifiability, Control-partial. Smart-collateral design increases upgrade surface.", "2026-06"], credora: ["c", "BBB", "Credit rating BBB. Strong engineering; shorter track record and team-key concentration.", "2026-08"], sphere: ["c", "B", "Technical B+, operational B−: admin key scope flagged.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["p", "◐", "Fluid earn vaults 6.4/10; DEX layer unscored.", "2026-06"], blockan: ["p", "◐", "Vault-level dashboards for USDC/ETH markets only.", "live"], curatorw: ["n"], defisaver: ["n"], pigi: ["c", "live", "Earn vaults tracked: risk-adjusted APY rank 8/50.", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Monitored: liquidity-layer utilization alerts.", "live"], llamarisk: ["n"] },
  gearbox: { defiscan: ["p", "queue", "Review in queue since 2026-05; preliminary notes published.", "2026-05"], defipunkd: ["c", "3/5", "Passes Exit, Open Access, Verifiability. Leverage architecture concentrates liquidation risk.", "2026-06"], credora: ["n"], sphere: ["c", "B−", "Operational B−: shrinking TVL base raises sustainability flag.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["p", "◐", "Passive pools tracked; credit accounts out of scope.", "live"], zyfai: ["n"], pharos: ["n"], llamarisk: ["n"] },
  euler: { defiscan: ["c", "Stage 1", "Stage 1 — immutable vault kernel; per-vault governor powers are the residual surface.", "2026-07"], defipunkd: ["c", "4/5", "Passes Control, Exit, Open Access, Verifiability. Autonomy partial on per-vault oracle choice.", "2026-06"], credora: ["c", "BBB+", "Credit rating BBB+. Post-mortem discipline and audit depth notable; v1 history priced in.", "2026-08"], sphere: ["c", "B+", "Technical A−; operational B on vault-governor variance.", "2026-05"], xerberus: ["c", "BBB", "Vault-level ratings across 22 EVK vaults, median BBB.", "2026-07"], risklayer: ["n"], philidor: ["c", "7.1", "Median vault score 7.1/10 across scored EVK set.", "2026-06"], blockan: ["c", "live", "Live dashboard: vault utilization, collateral chains, liquidation depth.", "live"], curatorw: ["p", "◐", "EulerEarn strategies tracked via curator lens.", "live"], defisaver: ["n"], pigi: ["c", "live", "EVK vaults tracked: exploit history flagged (v1, resolved).", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Monitored: 11 alert rules.", "live"], llamarisk: ["n"] },
  compound: { defiscan: ["c", "Stage 1", "Stage 1 — governance-gated upgrades with timelock; guardian scope documented.", "2026-07"], defipunkd: ["c", "4/5", "Passes four dimensions; Autonomy partial on price-feed admin.", "2026-06"], credora: ["c", "A", "Credit rating A. Long track record, conservative listings, slow-moving governance.", "2026-08"], sphere: ["c", "B+", "Composite B+ — technical strong, operational aging.", "2026-05"], xerberus: ["n"], risklayer: ["c", "81", "Attested 81/100.", "2026-08"], philidor: ["n"], blockan: ["c", "live", "Live dashboard: v2 wind-down exposure + v3 market health.", "live"], curatorw: ["n"], defisaver: ["c", "live", "v2/v3 position management live.", "live"], pigi: ["p", "◐", "v3 base markets only.", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Monitored: 8 alert rules.", "live"], llamarisk: ["c", "2 rpt", "2 reports on v2 deprecation risk.", "2026-03"] },
  liquity: { defiscan: ["c", "Stage 2", "Stage 2 — fully immutable, no admin keys, no governance surface. Reference implementation.", "2026-07"], defipunkd: ["c", "5/5", "Passes all five dimensions. v1 is the registry's canonical maximum-autonomy entry.", "2026-06"], credora: ["p", "◐", "v1 rated A− (immutability premium); v2 unrated pending post-incident review.", "2026-08"], sphere: ["c", "A", "Technical A+, operational A−.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["n"], blockan: ["c", "live", "Trove distribution + redemption pressure dashboard.", "live"], curatorw: ["n"], defisaver: ["c", "live", "Trove automation live for v1 and v2.", "live"], pigi: ["n"], zyfai: ["n"], pharos: ["p", "◐", "v2 monitored post-incident; v1 unmonitored (immutable).", "live"], llamarisk: ["c", "2 rpt", "BOLD peg dynamics review; v2.1 migration note.", "2026-02"] },
  uniswap: { defiscan: ["c", "Stage 1", "Stage 1 — immutable core; hook contracts shift risk to pool level, flagged per pool.", "2026-07"], defipunkd: ["c", "5/5", "Passes all five. v4 hooks noted as per-pool risk relocation, not protocol risk.", "2026-06"], credora: ["n"], sphere: ["c", "A−", "Technical A; operational A−.", "2026-05"], xerberus: ["n"], risklayer: ["c", "84", "Attested 84/100.", "2026-08"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["c", "live", "Pool-level security grades for top 200 v3/v4 pools.", "live"], pharos: ["c", "24/7", "Hook-deployment anomaly monitoring live.", "live"], llamarisk: ["n"] },
  curve: { defiscan: ["c", "Stage 1", "Stage 1 — immutable pools; DAO parameter surface with emergency scope time-bounded.", "2026-07"], defipunkd: ["c", "4/5", "Passes four; Verifiability partial on legacy pool zoo.", "2026-06"], credora: ["n"], sphere: ["c", "B+", "Composite B+; 2023 incident weighted in operational score.", "2026-05"], xerberus: ["n"], risklayer: ["c", "74", "Attested 74/100; legacy-pool heterogeneity deduction.", "2026-08"], philidor: ["n"], blockan: ["p", "◐", "crvUSD markets dashboard only.", "live"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["c", "live", "Pool risk grades across 180 Curve pools.", "live"], pharos: ["c", "24/7", "Monitored: pool imbalance + oracle alerts.", "live"], llamarisk: ["c", "12 rpt", "12 reports: crvUSD parameters, gauge risk, collateral onboarding reviews.", "2026-07"] },
  balancer: { defiscan: ["p", "v2", "v2 assessed Stage 0 pre-incident; v3 review scheduled.", "2026-06"], defipunkd: ["c", "3/5", "Passes Exit, Open Access, Verifiability. Control partial: emergency sub-DAO scope.", "2026-06"], credora: ["n"], sphere: ["c", "C+", "Operational C after Nov 2025 exploit; remediation tracked.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["c", "live", "Pool grades live; exploit-affected pools flagged historical.", "live"], pharos: ["c", "24/7", "Monitored: invariant deviation alerts added post-incident.", "live"], llamarisk: ["n"] },
  cowswap: { defiscan: ["p", "queue", "Intent-based settlement in scoping; solver set is the assessed surface.", "2026-06"], defipunkd: ["c", "4/5", "Passes Control, Exit, Open Access, Verifiability. Autonomy partial: permissioned solver set.", "2026-06"], credora: ["n"], sphere: ["c", "B+", "Technical A−; solver centralization noted.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["n"], pharos: ["p", "◐", "Settlement anomaly monitoring in beta.", "live"], llamarisk: ["n"] },
  oneinch: { defiscan: ["n"], defipunkd: ["c", "3/5", "Passes Open Access, Verifiability, Exit. Router deploy keys with team.", "2026-06"], credora: ["n"], sphere: ["c", "B", "Composite B; resolver incident weighted.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["n"], pharos: ["n"], llamarisk: ["n"] },
  zerox: { defiscan: ["n"], defipunkd: ["p", "2/5", "Assessment in progress: Open Access, Verifiability pass; remaining dims pending.", "2026-07"], credora: ["n"], sphere: ["c", "B−", "Composite B−; legacy governance surface.", "2026-05"], xerberus: ["n"], risklayer: ["n"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["n"], pharos: ["n"], llamarisk: ["n"] },
  yearn: { defiscan: ["c", "Stage 0", "Stage 0 — multisig-executed governance; strategy swap powers without user exit window.", "2026-07"], defipunkd: ["c", "3/5", "Passes Exit, Open Access, Verifiability.", "2026-06"], credora: ["n"], sphere: ["c", "B", "Composite B.", "2026-05"], xerberus: ["c", "A−", "Protocol-level A−; per-vault range BB…AA across 31 vaults.", "2026-07"], risklayer: ["n"], philidor: ["c", "7.4", "Median vault 7.4/10; code maturity vector strongest.", "2026-06"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["c", "live", "31 vaults tracked; risk-adjusted APY leader in 4 categories.", "live"], zyfai: ["p", "◐", "LP-facing vaults only.", "live"], pharos: ["p", "◐", "Strategy-change alerts in beta.", "live"], llamarisk: ["n"] },
  mellow: { defiscan: ["n"], defipunkd: ["p", "2/5", "Preliminary: Open Access, Verifiability pass; curator-power dims in review.", "2026-07"], credora: ["n"], sphere: ["n"], xerberus: ["c", "BB", "Protocol rating BB — curator concentration and restaking dependency chain.", "2026-07"], risklayer: ["n"], philidor: ["c", "6.2", "Median vault 6.2/10; governance-controls vector weakest.", "2026-06"], blockan: ["n"], curatorw: ["p", "◐", "Mellow-on-Morpho allocations visible via curator lens.", "live"], defisaver: ["n"], pigi: ["c", "live", "LRT vaults tracked; concentration warnings active.", "live"], zyfai: ["n"], pharos: ["n"], llamarisk: ["n"] },
  morphovaults: { defiscan: ["p", "layer", "Assessed as risk layer on Morpho Stage 1 core; per-vault curator powers are the surface.", "2026-07"], defipunkd: ["c", "4/5", "Passes four; Control partial — curator role centralization varies per vault.", "2026-06"], credora: ["p", "◐", "6 flagship vaults rated (A−…BBB−); long tail unrated.", "2026-08"], sphere: ["n"], xerberus: ["c", "A−", "Median A− across 48 rated MetaMorpho vaults.", "2026-07"], risklayer: ["n"], philidor: ["c", "8.1", "Median 8.1/10 — strongest cohort in the 700-vault set.", "2026-06"], blockan: ["p", "◐", "Aggregated exposure via Morpho dashboard.", "live"], curatorw: ["c", "live", "Full curator-behavior coverage: allocation drift, timelock usage, cap discipline.", "live"], defisaver: ["n"], pigi: ["c", "live", "48 vaults tracked with curator concentration metrics.", "live"], zyfai: ["n"], pharos: ["c", "24/7", "Curator-action alerts live.", "live"], llamarisk: ["p", "◐", "Covered within Morpho oracle-risk series.", "2026-05"] },
  pendle: { defiscan: ["c", "Stage 0", "Stage 0 — upgradeable markets behind timelock; admin scope documented but broad.", "2026-07"], defipunkd: ["c", "3/5", "Passes Open Access, Verifiability, Exit.", "2026-06"], credora: ["n"], sphere: ["c", "B+", "Technical A−: novel mechanism complexity priced.", "2026-05"], xerberus: ["c", "BBB+", "PT/YT market ratings across 60+ pools, median BBB+.", "2026-07"], risklayer: ["n"], philidor: ["c", "7.8", "LP vault cohort 7.8/10.", "2026-06"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["c", "live", "PT strategies tracked; implied-yield risk bands.", "live"], zyfai: ["p", "◐", "Selected pools graded.", "live"], pharos: ["c", "24/7", "Maturity-event and oracle alerts.", "live"], llamarisk: ["p", "◐", "One published note: PT collateral in lending markets.", "2026-01"] },
  lido: { defiscan: ["c", "Stage 1", "Stage 1 — dual governance gives stETH holders a credible veto/exit path.", "2026-07"], defipunkd: ["c", "4/5", "Passes four; Control partial pending full dual-governance rollout metrics.", "2026-06"], credora: ["c", "AA−", "Credit rating AA−: deepest liquidity in class, operator set diversified.", "2026-08"], sphere: ["c", "A−", "Composite A−.", "2026-05"], xerberus: ["c", "AA", "stETH rated AA — highest in LST cohort.", "2026-07"], risklayer: ["c", "91", "Attested 91/100 — top score in registry.", "2026-08"], philidor: ["n"], blockan: ["p", "◐", "stETH collateral markets tracked in lending dashboards.", "live"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["n"], pharos: ["c", "24/7", "Oracle quorum + withdrawal queue monitoring.", "live"], llamarisk: ["c", "6 rpt", "6 reports: operator concentration, dual governance review, depeg stress scenarios.", "2026-06"] },
  rocketpool: { defiscan: ["c", "Stage 1", "Stage 1 — oDAO powers time-bounded; permissionless node operator set.", "2026-07"], defipunkd: ["c", "4/5", "Passes four; Autonomy partial on oDAO oracle duties.", "2026-06"], credora: ["p", "◐", "rETH under review for institutional coverage.", "2026-08"], sphere: ["c", "B+", "Composite B+.", "2026-05"], xerberus: ["c", "A−", "rETH rated A−.", "2026-07"], risklayer: ["n"], philidor: ["n"], blockan: ["n"], curatorw: ["n"], defisaver: ["n"], pigi: ["n"], zyfai: ["n"], pharos: ["p", "◐", "Deposit-pool monitoring in beta.", "live"], llamarisk: ["n"] },
};

const toCell = (arr) => {
  if (!arr || arr[0] === "n") return { status: "n" };
  return {
    status: arr[0],
    label: arr[1] ?? null,
    verbatim: arr[2] ?? null,
    asOf: arr[3] ?? null,
    sourceUrl: null,
  };
};

write("data/feeds.json", {
  version: 1,
  updatedAt: "2026-08-20T00:00:00.000Z",
  feeds,
});

write("data/categories.json", {
  version: 1,
  categories: Object.values(categories),
});

for (const p of protocols) {
  write(`data/protocols/${p.id}.json`, {
    ...p,
    chain: "ethereum",
  });
}

for (const [protocolId, cells] of Object.entries(rawCov)) {
  const assessments = {};
  for (const [feedId, arr] of Object.entries(cells)) {
    assessments[feedId] = toCell(arr);
  }
  write(`data/coverage/${protocolId}.json`, {
    protocolId,
    updatedAt: "2026-08-20T00:00:00.000Z",
    assessments,
  });
}

write("data/live/tvl.json", {
  version: 1,
  source: "defillama",
  updatedAt: null,
  note: "Populated by the DefiLlama collector. Seed values are illustrative until first collect run.",
  protocols: Object.fromEntries(
    protocols.map((p) => [
      p.id,
      {
        tvlUsd: null,
        ethereumTvlUsd: null,
        volume24hUsd: null,
        defillamaSlug: p.defillamaSlug,
        tvlWithin: p.tvlWithin,
      },
    ]),
  ),
});

write("data/meta.json", {
  version: 1,
  project: "openrisk",
  chain: "ethereum",
  license: "AGPL-3.0",
  noCompositeScoring: true,
  seededFrom: "openrisk-mockup",
  protocolCount: protocols.length,
  feedCount: feeds.length,
});

console.log("done");
